{
 "title": "Bentocache",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hit rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(increase(bentocache_hits[$__range])) / (sum(increase(bentocache_hits[$__range])) + sum(increase(bentocache_misses[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Hits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(bentocache_hits[$__range]))",
     "legendFormat": "{{labelName}}"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Misses" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(bentocache_misses[$__range]))",
     "legendFormat": "{{labelName}}"
    }
   ]
  },
  {
   "title": "Cache Writes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Writes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(bentocache_writes[$__range]))",
     "legendFormat": "{{labelName}}"
    }
   ]
  },
  {
   "title": "Cache Deletes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Deletes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(bentocache_deletes[$__range]))",
     "legendFormat": "{{labelName}}"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Average Ops",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(bentocache_hits[$__range]) * 60)",
     "legendFormat": "Average hits"
    },
    {
     "expr": "sum(rate(bentocache_misses[$__range]) * 60)",
     "legendFormat": "Average misses"
    },
    {
     "expr": "sum(rate(bentocache_writes[$__range]) * 60)",
     "legendFormat": "Average writes"
    },
    {
     "expr": "sum(rate(bentocache_deletes[$__range]) * 60)",
     "legendFormat": "Average deletes"
    }
   ]
  },
  {
   "title": "Lowest hit rates",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bottomk(10, 100 * increase(bentocache_hits[$__range]) / (increase(bentocache_hits[$__range]) + increase(bentocache_misses[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Highest hit rates",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, 100 * increase(bentocache_hits[$__range]) / (increase(bentocache_hits[$__range]) + increase(bentocache_misses[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top missed keys",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (key) (rate(bentocache_misses[$__range]) * 60) and topk(10, sum by (key) (increase(bentocache_misses[$__range]@end())))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top hitted keys",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (key) (rate(bentocache_hits[$__range]) * 60) and topk(10, sum by (key) (increase(bentocache_hits[$__range]@end())))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}