global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 5s
scrape_configs:
- job_name: playground-app
  metrics_path: /metrics
  scheme: https
  static_configs:
  - targets: ['employees-projectors-reason-finland.trycloudflare.com']
    labels:
      service: 'app'
